### ISSUE TITLE
undefined reference to `_mkgmtime'

### ISSUE THREAD

**Issue by NCJECulver** [ogdenpm/mlbr#1]
Running Ubuntu 23.10 (Mantic Minotaur). 
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0

~/temp/mlbr-master$ gcc -o mlbr *.c
uncrunch.c: In function ‘getCrunchTime’:
uncrunch.c:136:12: warning: implicit declaration of function ‘_mkgmtime’; did you mean ‘gmtime’? [-Wimplicit-function-declaration]
  136 |     return _mkgmtime(&timebuf);
      |            ^~~~~~~~~
      |            gmtime
/usr/bin/ld: /tmp/ccV5L0VC.o: in function `getCrunchTime':
uncrunch.c:(.text+0x184): undefined reference to `_mkgmtime'
collect2: error: ld returned 1 exit status

This fixed it for me:

#include <time.h>

and replaced 
return _mkgmtime(&timebuf);

with

if defined(_WIN32) || defined(_WIN64)
    return _mkgmtime(&timebuf);
#else
    return timegm(&timebuf);
#endif

**Comment by ogdenpm** [comment]
Fixed by replacing the _mkgmtime with timegm. I had already converted the others, this one was missed.
